import { getMongoClient } from "./mongodb";
import { decryptData, hashData } from "./encryption";
import { AgreementRecord } from "./types";

export async function retrieveAgreementRecord(recordId: string) {
  try {
    const client = await getMongoClient();
    const db = client.db(process.env.MONGODB_DB);

    const { ObjectId } = await import("mongodb");
    const record = await db
      .collection<AgreementRecord>("agreement_records")
      .findOne({ _id: new ObjectId(recordId) });

    if (!record) {
      return null;
    }

    // Decrypt sensitive fields
    return {
      _id: record._id,
      email: decryptData(record.email),
      name: decryptData(record.name),
      userType: record.userType,
      agreedToTerms: record.agreedToTerms,
      agreedToPrivacy: record.agreedToPrivacy,
      termsVersion: record.termsVersion,
      privacyVersion: record.privacyVersion,
      ipAddress: decryptData(record.ipAddress || ""),
      userAgent: decryptData(record.userAgent || ""),
      timestamp: record.timestamp,
      documentHash: record.documentHash,
    };
  } catch (error) {
    console.error("Error retrieving agreement record:", error);
    throw error;
  }
}

export async function retrieveUserAgreements(email: string) {
  try {
    const client = await getMongoClient();
    const db = client.db(process.env.MONGODB_DB);

    // Get all records for this email (encrypted)
    const encryptedEmail = (await import("./encryption")).encryptData(email);
    const records = await db
      .collection<AgreementRecord>("agreement_records")
      .find({ email: encryptedEmail })
      .sort({ timestamp: -1 })
      .toArray();

    // Decrypt records for display
    return records.map((record) => ({
      _id: record._id,
      email: decryptData(record.email),
      name: decryptData(record.name),
      userType: record.userType,
      agreedToTerms: record.agreedToTerms,
      agreedToPrivacy: record.agreedToPrivacy,
      termsVersion: record.termsVersion,
      privacyVersion: record.privacyVersion,
      ipAddress: decryptData(record.ipAddress || ""),
      userAgent: decryptData(record.userAgent || ""),
      timestamp: record.timestamp,
      documentHash: record.documentHash,
    }));
  } catch (error) {
    console.error("Error retrieving user agreements:", error);
    throw error;
  }
}

export async function verifyAgreementIntegrity(record: any): Promise<boolean> {
  try {
    // Verify document hash hasn't been tampered with
    const expectedHash = hashData(
      `${record.email}:${record.name}:${record.userType}:${record.agreedToTerms}:${record.agreedToPrivacy}`,
    );

    return expectedHash === record.documentHash;
  } catch (error) {
    console.error("Error verifying agreement integrity:", error);
    return false;
  }
}

export function formatCourtDocument(record: any): string {
  const verifiedStatus = "✓ Document integrity verified";

  return `
================================================================================
                    AGREEMENT VERIFICATION DOCUMENT
                         StudentHousing NG Platform
================================================================================

RECORD ID: ${record._id}
TIMESTAMP: ${new Date(record.timestamp).toLocaleString()}
STATUS: ${verifiedStatus}

USER INFORMATION:
  Name: ${record.name}
  Email: ${record.email}
  User Type: ${record.userType.toUpperCase()}
  IP Address: ${record.ipAddress}
  User Agent: ${record.userAgent}

AGREEMENT STATUS:
  ✓ Agreed to Terms & Conditions (v${record.termsVersion}): ${record.agreedToTerms ? "YES" : "NO"}
  ✓ Agreed to Privacy Policy (v${record.privacyVersion}): ${record.agreedToPrivacy ? "YES" : "NO"}

SECURITY VERIFICATION:
  Document Hash: ${record.documentHash}
  
  This hash verifies the authenticity of this record. Any modification to the
  user information or agreement status will change this hash.

LEGAL NOTICE:
  This document serves as official evidence that the above-named individual
  explicitly agreed to the Platform's Terms & Conditions and Privacy Policy
  on the date and time specified above. The agreement was recorded with
  encryption and cryptographic verification to ensure integrity.

================================================================================
Generated by StudentHousing NG Legal Compliance System
For court or legal proceedings use only.
================================================================================
`;
}
